import { Platform } from 'react-native';
import {
  IOS_FIREBASE_API_KEY,
  IOS_FIREBASE_PROJECT_ID,
  IOS_FIREBASE_STORAGE_BUCKET,
  IOS_FIREBASE_MESSAGING_SENDER_ID,
  IOS_FIREBASE_APP_ID,
  IOS_FIREBASE_DATABASE_URL,
  ANDROID_FIREBASE_API_KEY,
  ANDROID_FIREBASE_PROJECT_ID,
  ANDROID_FIREBASE_STORAGE_BUCKET,
  ANDROID_FIREBASE_MESSAGING_SENDER_ID,
  ANDROID_FIREBASE_APP_ID,
  ANDROID_FIREBASE_DATABASE_URL,
} from '@env';

const getConfigValue = (iosValue: string, androidValue: string): string => {
  return Platform.OS === 'ios' ? iosValue : androidValue;
};

export const firebaseConfig = {
  apiKey: getConfigValue(IOS_FIREBASE_API_KEY, ANDROID_FIREBASE_API_KEY),
  projectId: getConfigValue(IOS_FIREBASE_PROJECT_ID, ANDROID_FIREBASE_PROJECT_ID),
  storageBucket: getConfigValue(IOS_FIREBASE_STORAGE_BUCKET, ANDROID_FIREBASE_STORAGE_BUCKET),
  messagingSenderId: getConfigValue(IOS_FIREBASE_MESSAGING_SENDER_ID, ANDROID_FIREBASE_MESSAGING_SENDER_ID),
  appId: getConfigValue(IOS_FIREBASE_APP_ID, ANDROID_FIREBASE_APP_ID),
  databaseURL: getConfigValue(IOS_FIREBASE_DATABASE_URL, ANDROID_FIREBASE_DATABASE_URL),
}; 